name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_HUB_REPOSITORY }}:$(date +%s)
    - name: Unit Test
      run: docker run --name unit_test ${{ secrets.DOCKER_HUB_REPOSITORY }}:$(date +"%s") -d www.google.com -p 443 -vvv 
    - name: rm test job
      run: docker rm unit_test
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        repository: ${{ secrets.DOCKER_HUB_REPOSITORY }}
        tag_with_ref: true

